volumes:
#  openduty_mysql_data: {}
  openduty_postgres_data: {}
  openduty_redis_data: {}


services:
  app:
    image: harbor.app.clemson.edu/dockerhub-proxy/openduty/openduty:latest
    working_dir: /openduty
    build: devops/deploy
    command: python3 ./manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - openduty-postgres
      - openduty-redis
   

  openduty-postgres:
    container_name: openduty-postgres
    build: ./devops/docker/postgres
    restart: always
    volumes:
      - openduty_postgres_data:/var/lib/postgresql/data
    environment:

  openduty-redis:
    container_name: openduty-redis
    restart: always
    build:
      context: ./devops/docker/redis/
    volumes:
      - openduty_redis_data:/data
    ports:
      - 6379:6379